mate85-vagas/vagas-backend

- src/controllers/Users.js
Altera a mensagem de "Acesso não autorizado" escrita em inglês para português nas linhas 65 e 69 no script src/controllers/Users.js
> update: traduz mensagem  de acesso negado

- src/controllers/Users.js
Alterações realizadas por Yuri e Bruno e editadas juntamente comigo, merge forçado.
> Update: Email verification added

- .eslintrc.json
- .prettierrc
- README.md
- docker-compose.yml
- env.example
- package-lock.json
- package.json
- src/controllers/Jobs.js
- src/controllers/Users.js
- src/index.js
- src/routes/healthCheckRoutes.js
- src/routes/userRoutes.js
- swagger.yml
> Implementa melhorias na API

- src/models/ProfileModel.js
Adiciona a relação entre Profile - User.
> add: relacao 1:1 Profile - User

- src/controllers/Profiles.js
- src/repositories/ProfileRepository.js
- src/routes/profileRoutes.js
Implementado funções de criação e deleção de perfil. Feito juntamente com Bruno Di Paolo.
> Add: funções para criação e deleção de perfil

- .gitignore
- babel.config.cjs
- jest.config.cjs
- package-lock.json
- package.json
- src/__tests__/units/factory/job-model-factory.js
- src/__tests__/units/repositories/job-repository.spec.js
Adiciona configuração de testes.
Observação: foi implementado um teste de unidade para validar configuração.
> test: add test config

- src/controllers/Jobs.js
- src/controllers/Profiles.js
- src/controllers/Users.js
Retornos de mensagem de erro agora tem propriedade "error: true."
> Update: adicionado propriedade 'error' nas mensagens de erro.

- src/controllers/Skills.js
- src/index.js
- src/models/SkillAttrs.js
- src/models/SkillModel.js
- src/repositories/SkillRepository.js
- src/routes/skillRoutes.js
Adiciona o que foi requisitado: model, repository, route, e controller para habilidades.
> Add: Cria model, repository, route, e controller para habilidades.

- src/__tests__/units/factory/user-job-model-factory.js
- src/__tests__/units/repositories/job-repository.spec.js
Adicionado auto-testes para as funções em JobRepository.
> Add: auto-testes para JobRepository

- src/controllers/Technologies.js
- src/repositories/TechnologyRepository.js
- src/repositories/UserRepository.js
- src/routes/technologyRoutes.js
- src/routes/userRoutes.js
- swagger.yml
Finaliza entrega parcial da documentação.
> Documentação parcial da API

- src/__tests__/units/factory/skill-model-factory.js
- src/__tests__/units/factory/technology-model-factory.js
- src/__tests__/units/repositories/job-repository.spec.js
- src/__tests__/units/repositories/skill-repository.spec.js
- src/__tests__/units/repositories/technology-repository.spec.js
- src/controllers/Technologies.js
- src/repositories/TechnologyRepository.js
Adicionado testes unitários para SkillRepository e TechnologyRepository.
Também inclui um pequeno fix nos testes unitários de JobRepository e um fix na nomenclatura da função createBulkTechnologies.
> Add: testes unitários para Skill e Technology

- email.html
- package-lock.json
- package.json
- src/utils/emailSender.js
Cria um arquivo email.html contendo a estilização do e-mail, e o importa para alteração e envio.
> Adiciona a estilização do email

- env.example
- src/controllers/Users.js
- src/models/UserAttrs.js
- src/models/UserModel.js
- src/repositories/User_JobRepository.js
Adicionado filtros de paginação e quantidade de itens por página nos endpoints de vagas_aplicadas e vagas_criadas.
> Add: filtro de paginação e quantidade de itens por página nos endpoints de vagas_aplicadas e vagas_criadas

- email.html
- inviteEmail.html
- src/controllers/Users.js
- src/routes/userRoutes.js
- src/utils/emailSender.js
Funções foram adicionadas no emailSender. Nestas funções haverá repetição de código, dado que, a entrega é até amanhã e a funcionalidade de invite veio depois do email de aplicação de vaga. Além disso, um novo html "inviteEmail.html" foi adicionado.
> Adiciona rota para invite e a função correspondente

- src/controllers/Jobs.js
- src/controllers/Profiles.js
- src/controllers/Users.js
- src/repositories/JobRepository.js
- src/repositories/UserRepository.js
- src/routes/userRoutes.js
- src/utils/auth.js
Adiciona propriedade de controle de administrativo ao token.
Adiciona nova regra para atualização e deleção de vagas e usuários.
> feat: implement access control

- src/controllers/EmailLists.js
- src/controllers/Users.js
- src/index.js
- src/repositories/EmailListRepository.js
- src/routes/emailListRoutes.js
Adicionado arquivo controller e routes para o model EmailList.
Ainda é necessário o repository para testar.
> Add: Controller, routes e repository de EmailList

- src/controllers/EmailLists.js
Atualizado o controller EmailLists para utilizar a informação isAdmin do token.
> Update: Funções do controller EmailLists agora utilizam token para pegar isAdmin

- src/controllers/Users.js
Altera o UserController na função getAllUsers para apenas adms poderem acessar.
> Altera para o getAllUsers para apenas administradores poderem acessar o endpoint

- src/repositories/JobRepository.js
- src/utils/emailSender.js
- vagaCriada.html
Altera o emailSender e o Job repository com a chamada da função e a definição das opções de email.
> Adiciona o envio de email para uma lista de emails ao criar uma vaga

- src/__tests__/units/factory/email-list-model-factory.js
- src/__tests__/units/repositories/email-list-repository.spec.js
Adicionado testes unitários do repositório EmailList.
> Add: Teste unitários EmailList

- src/controllers/Jobs.js
Mudado de minúsculo para maiúsculo.
> Fix: mensagem de atualização de vaga

- src/controllers/EmailLists.js
Altera o código do getAllEmailList para autorizar o acesso ao endpoint por qualquer usuário que esteja logado.
> REFAC: altera getAllEmailList para ser acessado por qualquer usuário logado
